language: objective-c
osx_image: xcode7.3
# before_install:
    # - brew update
    # - brew install xctool
script:
    - xcodebuild -showsdks
    - xcodebuild clean build test -workspace Example/HMAMessageViewManager.xcworkspace -scheme HMAMessageViewManager-Tests -sdk iphonesimulator9.3 ONLY_ACTIVE_ARCH=NO

notifications:
  email:
    recipients:
      - jki@jki.lv
    on_success: never # [always|never|change]
    on_failure: change # [always|never|change]
