language: objective-c
# before_install:
    # - brew update
    # - brew install xctool
script:
    - xcodebuild clean build test -workspace Example/HMAMessageViewManager.xcworkspace -scheme HMAMessageViewManager-Tests  -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO

notifications:
  email:
    recipients:
      - jki@jki.lv
    on_success: never # [always|never|change]
    on_failure: change # [always|never|change]
